export const defaultAgents = [
    {
        id: 'agent-forge',
        name: 'Forge',
        role: 'Universal Coding Copilot',
        description: 'The all-purpose builder. Handles coding, debugging, architecture, setup guidance, technical explanations, and general problem solving when a specialist agent is not the best fit.',
        category: 'Technical',
        color: '#38bdf8',
        tools: [],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
    {
        id: 'agent-scout',
        name: 'Scout',
        role: 'Web Researcher',
        description: 'The internet searcher. Finds real, current, cited information using live web search. Never guesses.',
        category: 'Research',
        color: '#00d4ff',
        tools: ['web_search'],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
    {
        id: 'agent-quill',
        name: 'Quill',
        role: 'Email Writer',
        description: 'The professional email specialist. Takes any information and transforms it into a perfect, ready-to-send email.',
        category: 'Creative',
        color: '#a78bfa',
        tools: ['email_draft'],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
    {
        id: 'agent-sage',
        name: 'Sage',
        role: 'Task Planner',
        description: 'The strategic planning specialist. Breaks any goal into a specific, prioritized, time-estimated action plan.',
        category: 'Business',
        color: '#f59e0b',
        tools: ['todo'],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
    {
        id: 'agent-atlas',
        name: 'Atlas',
        role: 'Data Calculator',
        description: 'The numbers specialist. Performs calculations with exact formulas and step-by-step verification. Never guesses.',
        category: 'Technical',
        color: '#34d399',
        tools: ['calculator'],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
    {
        id: 'agent-lens',
        name: 'Lens',
        role: 'Summarizer',
        description: 'The distillation specialist. Takes any length of content and extracts exactly the 5 most important points as clean bullets.',
        category: 'Analysis',
        color: '#f472b6',
        tools: ['summarizer'],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
    {
        id: 'agent-hermes',
        name: 'Hermes',
        role: 'Scheduler',
        description: 'The automation specialist. Schedules tasks and manages recurring agent runs with clear delivery confirmations.',
        category: 'Automation',
        color: '#f97316',
        tools: ['scheduler'],
        memory: [],
        createdAt: new Date().toISOString(),
        isDefault: true,
    },
];
